apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: shoppingapp-ns
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: shoppingapp-ns
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-app
          image: shopping-microservices-gateway:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Docker
