kind: Service
apiVersion: v1
metadata:
  name: identity-service-db
  namespace: shoppingapp-ns
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: identity-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db-deployment
  namespace: shoppingapp-ns
  labels:
    app: identity-db
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
      - name: identity-db
        image: postgres:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: shoppingapp-config-map
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: shoppingapp-config-map
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shoppingapp-secret
              key: POSTGRES_PASSWORD
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: identity-db-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: identity-db-storage
        persistentVolumeClaim:
          claimName: identity-db-pvc