apiVersion: v1
kind: Service
metadata:
  name: catalog-service-db
  namespace: shoppingapp-ns
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: catalog-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db-deployment
  namespace: shoppingapp-ns
  labels:
    app: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: catalog-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-config-map
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-config-map
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shoppingapp-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: catalog-db-storage
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: catalog-db-storage
          persistentVolumeClaim:
            claimName: catalog-db-pvc
      restartPolicy: Always

